-- Make order_number and quote_number generated by default so they can be omitted on insert
ALTER TABLE public.orders ALTER COLUMN order_number SET DEFAULT '';
ALTER TABLE public.wholesale_quotes ALTER COLUMN quote_number SET DEFAULT '';